### ISSUE TITLE
http-get can't handle encodings other than utf-8 correctly

### ISSUE THREAD

**Issue by futurend** [SaltwaterC/http-request#10]
streams encoded with anything other than utf-8 will fail loading.
I think that can be corrected if we detect the encoding and set the buffer options.encoding to binary if it's other than utf-8, but I can't figure out the right place to do that.
Has anybody tried this?

**Comment by SaltwaterC** [comment]
Have to update the docs to reflect the changes for v0.4. options.bufferType enables you do get the buffer as Buffer object which represents the raw data. The String buffers are default due to backward compatibility reasons. The binary encoding for String is deprecated:

<blockquote>
'binary' - A way of encoding raw binary data into strings by using only the first 8 bits of each character. This encoding method is deprecated and should be avoided in favor of Buffer objects where possible. This encoding will be removed in future versions of Node.
</blockquote>

I think I'll deprecate the String buffers, then migrate to a single Buffer implementation that provides the "one size fits all" approach.

**Comment by futurend** [comment]
That would clear things a bit.
Thanks.

**Comment by SaltwaterC** [comment]
https://github.com/SaltwaterC/http-get/wiki/Options-object - the updated documentation explains all the stuff about the encoding and were the library is going.
