### ISSUE TITLE
result.url not set?

### ISSUE THREAD

**Issue by karli2000** [SaltwaterC/http-request#18]
Hi,

the documentation says that result (if successful, of course) contains the final url that was used in result.url, but it looks like this is not set, or am i wrong?

Thank you,
Max

**Comment by SaltwaterC** [comment]
Hi,

result.url is only set when there's a HTTP redirect. It was meant as a measure to indicate that there was at least one redirect. Added as an afterthought. Not the happiest decision. Otherwise, the actual URL equals with the input (options.url) therefore does not make sense to include it into the response object.

The future http-get (actually http-request) is [nearly complete](https://github.com/SaltwaterC/http-get/blob/http-request/TODO.md) (nearly all the features of http-get). It is a complete rewrite of the library with room for adding other HTTP methods. It has a better response object that includes the [number of actual requests](http://saltwaterc.github.io/http-get/module-request.html#stdResult) before the response was passed to the completion callback. After finishing it and doing some code cleanup, I'm going to push it as the http-get replacement, without all those pesky deprecation warnings.

Regards,
Ștefan

**Comment by karli2000** [comment]
Ah, ok, i knew there was something wrong on my side!
Thank you for explaining!
And i can't wait for the new http-request, keep up the good work, http-get is by far the best lib for http request for nodejs!

Max

**Comment by SaltwaterC** [comment]
Published [http-request](https://npmjs.org/package/http-request) as beta since it isn't feature complete, but it supersedes http-get as it has all its features and test coverage. The feedback is welcome.

**Comment by karli2000** [comment]
Hi,

have replaced in my crawler http-get with http-request and it works perfect
(making around 200-400k requests a day)!
I don't  have the stream.push() error anymore (but maybe because of node
0.10.12). I only get sometimes a "incorrect header check"-errors but not
sure if it comes from http-request.

Great work!

Thank you,
Max

**Comment by SaltwaterC** [comment]
Hi,

The "incorrect header check" errors come from the zlib library. The library should reissue the request to a plain resource if the stream fails and the content is encoded, but sometimes the servers don't obey the accept-encoding header. However, a warning should be logged into STDERR in this case. If you can share some URLs that consistently fail with this error, I could see if there's a possible workaround.

Regards,
Ștefan

**Comment by karli2000** [comment]
Hi,

ok, so when i disable gzip compression it should go away? Where not able
yet to catch one of the urls, as soon as i have one i will send it to you!

Thank you,
Max

**Comment by SaltwaterC** [comment]
Some applications send encoded content even when accept-encoding isn't specified though. It may reduce the error rate with some really broken stuff. If you don't crawl content that usually is encoded (ie: html), then the support for gzip decoding doesn't help much. For html it reduces the needed bandwidth. A lot.
