### ISSUE TITLE
NodeJS dep

### ISSUE THREAD

**Issue by toots** [SaltwaterC/http-request#21]
Hi guys,

Any particular reason to block node requirement to `v0.6.11`? Any used API not in `v0.6.10`?

**Comment by SaltwaterC** [comment]
Hi. It is documented into the [README.md](https://github.com/SaltwaterC/http-get#system-requirements). I wouldn't use anything under 0.8.5 though. And 0.10.x is still too unstable due to Stream v2. Kinda like 0.6 was with HTTP v2 - a minefield.

The future version, aka the http-request rewrite requires 0.8.5 due to it's migration to a building block for RESTful services where this stuff about proper SSL is really important.

**Comment by toots** [comment]
Right sorry for the noise guys.
