### ISSUE TITLE
bufferType = "string" is deprecated

### ISSUE THREAD

**Issue by pijusn** [SaltwaterC/http-request#22]
When using `http.get(options, callback)`, I get this warning in my console:

```
Warning: The options.bufferType = "string" option is deprecated. Use options.bufferType = "buffer"; instead.
```

Node version: v0.10.15
Module versions:

```
├─┬ http-get@0.5.10
│ ├── buffer-concat@0.0.1
│ └── semver@2.1.0
```

**Comment by SaltwaterC** [comment]
The warning is self explanatory. The String buffers are deprecated due to possible issues with binary data where Buffers do it properly. They're also more difficult to expose in a different encoding than UTF-8.

The library will support only Buffer instances from v0.6 (http-request - available as beta / into the http-request branch). Getting a String is as easy as calling [Buffer.toString()](http://nodejs.org/api/buffer.html#buffer_buf_tostring_encoding_start_end). Which kinda is implicit for the String buffers since:

``` javascript
// a minimal implementation of what's happening into the lib with a http.js response
body = "";
response.on('data', function (chunk) {
  console.log(chunk typeof Buffer); // prints true
  body += chunk; // Buffer gets coerced to a String automatically
});
```

There should be only one way to buffer data. Till the migration is done, you have to keep the options.bufferType = "buffer" since the String buffer was default and I hate to break existing code without warning when http-request is released.
