### ISSUE TITLE
[Feature] Progress event

### ISSUE THREAD

**Issue by matylla** [SaltwaterC/http-request#8]
You can read bytes expected (from content-length header) and bytes received so far. Would be especially useful for downloading huge files.

``` javascript
http.on('progress', function(bytesExpected, bytesTotal) {
  // => logic
});
```

**Comment by SaltwaterC** [comment]
I had a discussion about it, but can't seem to find it. In order to work that way, a response object must be returned by http.get itself, and that object to be an EventEmitter instance. The implementation is not what I call straight forward, but I think it is doable with the current API. If it turns out to be too difficult to implement for the current state of affairs, a passed callback to the options object should do the trick way much easier.

Anyway, most probably it is going to be part of v0.4 which targets node.js v0.6.x and its native zlib support. I am pretty sick of the node.js v0.4 HTTP verbage.

**Comment by matylla** [comment]
Do you have any roadmap in mind? Would be nice to know when the v0.4 will be live.

**Comment by SaltwaterC** [comment]
Unfortunately no. For the moment my schedule is full with priority tasks. I'd hate to give you an estimation and not being able to follow it.

PS: adding a callback to the options object is fairly trivial. I could add it pretty quick if you're OK with it.

**Comment by matylla** [comment]
Yes please.

**Comment by SaltwaterC** [comment]
I added the functionality in the dev branch. I also plan to quickly fix #7. Shall be released pretty soon for public consumption.

PS: I really need to get to v0.4. v0.3 is turning into an unmaintainable mess.

**Comment by matylla** [comment]
> I really need to get to v0.4. v0.3 is turning into an unmaintainable mess.

I know exactly what you mean :) Thanks for a quick fix.

**Comment by SaltwaterC** [comment]
If there's no Content-Lenght, then the total is 0.

``` javascript
var http = require('http-get')

var progress = function (current, total) {
    console.log(current, total)
}

http.get({
    url: process.argv[2],
    progress: progress
}, process.argv[3], function (err, res) {
    if (err) {
        console.error(err)
    } else {
        console.log(res)
    }
})
```

Simple script showing the new functionality. Example:

``` bash
node http.js http://wordpress.org/latest.tar.gz wordpress.tar.gz
```

I picked this specifically since it doesn't have a Content-Lenght header. Also tested it with:

``` bash
node http.js http://mirrors.xservers.ro/ubuntu/releases//precise/ubuntu-12.04-beta2-desktop-i386.iso ubuntu-12.04-beta2-desktop-i386.iso
```

This does some real traffic over the network interface :).
